FROM mitchty/alpine-ghc:7.10

MAINTAINER t.ashula <t.ashula+github@gmail.com>

RUN apk add --no-cache build-base

RUN mkdir -p /usr/src/hadolint
WORKDIR /usr/src/hadolint

# # ------------------------------------------------------------
# # Build & Test
# # ------------------------------------------------------------

# Obtain the dependencies first, which are less likely to change, in order to reduce
# subsequent build time by leveraging image cache. This benefits developers when they
# build their code with this image locally. In case of Travis CI, this doesn't help
# reduce building time because Travis CI doesn't use cache.
COPY hadolint.cabal .
RUN cabal update && cabal install --only-dependencies --enable-tests

# Copy the rest of the source files, including hadolint.cabal again but doesn't matter
COPY . .

# Build
RUN cabal install

# Test
# RUN stack testa
RUN cabal test

# # ------------------------------------------------------------
# # Set PATH
# # ------------------------------------------------------------

# Add runtime path to easily reach the executable file. This only exists during build.
ENV PATH "/root/.cabal/bin:$PATH"

# Make it permanent for someone who login to the container of this image
RUN echo "export PATH=${PATH}" >>  /etc/profile

# # ------------------------------------------------------------
# # Extract Binaries
# # ------------------------------------------------------------

# Get hadolint binary
RUN mkdir -p /package/bin/
RUN cp $(which hadolint) /package/bin/

# Get shared libraries using magic
RUN mkdir -p /package/lib/
RUN ldd $(which hadolint) | grep "=> /" | awk '{print $3}' | xargs -I '{}' cp -v '{}' /package/lib/


# Copy hadolint package out to mounted directory
CMD ["cp", "-avr", "/package", "/mnt/"]
